.base: &base
  forwardAgent: true
  multiplexing: true

167.172.78.154: &dev1
  <<: *base
  stage: "develop"
  user: "root"
  port: 22
  identityFile: "~/.ssh/server-key"
  deploy_path: "/var/www/{{application}}"
  branch: "develop"

